### ISSUE TITLE
Installtion Error

### ISSUE THREAD

**Issue by mostafaasadi** [yousefvand/plasmoid-persian-calendar#1]
Hi
thank you for your usefull widget :rose: 
a few days ago I installed persian calender 1.1.0 and it work perfectly
today I tried to update and reinstall 1.2 version but I got this error
![1](https://user-images.githubusercontent.com/12208050/90975378-d5776880-e548-11ea-8585-7099ad7580eb.png)

**Comment by yousefvand** [comment]
Closing on assumption that the raiser has resolved the issue.
