### ISSUE TITLE
Calendar and Islamic prayer time 

### ISSUE THREAD

**Issue by amirahmadMohamadi** [yousefvand/plasmoid-persian-calendar#11]
Thanks for your widget. 
Simple and useful.

I would like to ask if it is possible to add calendar events and/or prayer times t this widget?

**Comment by MasterKia** [comment]
@amirahmadMohamadi 

You could use https://github.com/amirnajaffi/shamsi-calendar-plasmoid/

**Comment by amirahmadMohamadi** [comment]
Thanks. Very close to what I need.
