### ISSUE TITLE
Not work on plasma 6

### ISSUE THREAD

**Issue by erfan-star-1999** [yousefvand/plasmoid-persian-calendar#12]
Please update your code. it's not good left behind a useful project like this

**Comment by peyman-ar** [comment]
Hi
thank you for developing persian calander, It's really the best in kind, 
I want to know that, do you have any plan to support plasma 6 or not?

**Comment by yousefvand** [comment]
Hello. I'm aware of the issue. Unfortunately I'm very busy and can work on this project on my spare time. The good news is the man part of project has been completed successfully. There is a known issue that configuration page is blank. I may release what has been done as version 2.0.0 and when the project is completed release the final release as version 2.0.1
