### ISSUE TITLE
Unsupported widget on Kubuntu 24.10 - KDE 6.1

### ISSUE THREAD

**Issue by mehdiMj-ir** [yousefvand/plasmoid-persian-calendar#14]
I just updated my OS `Kubuntu 24.10` with `KDE 6.1.5` and it say this extension is old and not supported.
I tried reinstalling the latest version **v2.1.0** but it didn't work and I got following error:
```info
Installing the package /home/mehdi/org.kde.plasma.persian-calendar.plasmoid failed.
```

**Comment by yousefvand** [comment]
There are two versions of this plasmoid. one for kde5 and one for kde6. I'm running Archlinux with latest KDE6 and using this plasmoid without problem. goto https://www.pling.com/p/2165655/ and download 6.x version file.
