### ISSUE TITLE
Add feature or variable in source code to change FORMAT

### ISSUE THREAD

**Issue by mhkarimi1383** [yousefvand/plasmoid-persian-calendar#5]
there is two way that we can change Date format:
1. use widget settings
2. tweak the source code

I prefer first one but I want to know if there is a way to change that format using first way (source code and rebuild)

**Comment by yousefvand** [comment]
Just created [another project](https://github.com/yousefvand/persian-date-parser) as a general purpose **Persian date parser** and it is almost done. I'm gonna use it in this project. Using CSS styling and this parser you can almost make any representation you like. The configuration code is already finished and ready in [dev](https://github.com/yousefvand/plasmoid-persian-calendar/tree/dev) branch.
