### ISSUE TITLE
wrong size in left side panel

### ISSUE THREAD

**Issue by lordkian** [yousefvand/plasmoid-persian-calendar#8]
hi.
I'm using Manjaro KDE. The main panel is on the left side. Only month is visible.

**Comment by yousefvand** [comment]
Hi, is there enough space on the panel for the widget. Can you attach a screenshot?

**Comment by yousefvand** [comment]
Assuming the problem had been lack of enough space on the panel, and the problem is solved, I'm closing this issue.
