### ISSUE TITLE
change in the width of the widget because of non-monospaced vazir font

### ISSUE THREAD

**Issue by mh-firouzjaah** [yousefvand/plasmoid-persian-calendar#9]
Hello and thank you for this great plasmoid (Persian Calendar)
I found that the `pj` prefix also works for the clock format, and setting the update interval to 1s also gives me the clock in seconds. But since the `vazir` font is not monospace, change of the number per unit also changes the overall width of the widget, so I changed the font to` cascadia code pl`, which has recently added Arabic / Urdu language support. This is not a good `vazir` font but it still works and is good.

I would like to ask if it is possible to add the full month/year `calendar` and `events` part, such as what the `event calendar` or the default `digital clock` plasmoids currently have.
best regards.

**Comment by yousefvand** [comment]
For the first part of your request I can make it happen in the next release but for the events part, this calendar name has a **simple** prefix and I want it to remain so.

**Comment by yousefvand** [comment]
v1.3.3 closes this issue
